export const initialState = {
	expenses: null,
	yearWiseExpenses: {},
	monthWiseExpenses: {},
	focusedExpense: {},
	error: null,
	currentYear: new Date().getFullYear(),
	currentMonth: new Date().getMonth() + 1,
	gettingExpenses: false,
	gettingExpense: false,
	creatingExpense: false,
	updatingExpense: false,
	deletingExpense: false,
	isGettingYearWiseExpenses: false,
	isGettingMonthWiseExpenses: false,
};
