export const initialState = {
  expenses: [],
  yearWiseExpense: {},
  monthWiseExpense: {},
  focusedExpense: {},
  categoryWiseExpensesForChart: [],
  categoryWiseExpensesForChartError: '',
  dayWiseExpensesForChart: [],
  dayWiseExpensesForChartError: '',
  monthWiseExpensesForChart: [],
  monthWiseExpensesForChartError: '',
  yearWiseExpensesForChart: [],
  yearWiseExpensesForChartError: '',
  error: null,
  currentYear: new Date().getFullYear(),
  currentMonth: new Date().getMonth() + 1,
  gettingExpenses: false,
  gettingExpense: false,
  creatingExpense: false,
  updatingExpense: false,
  deletingExpense: false,
  gettingYearWiseExpense: false,
  gettingMonthWiseExpense: false,
  gettingCategoryWiseExpenseForChart: false,
  gettingDayWiseExpenseForChart: false,
  gettingMonthWiseExpenseForChart: false,
  gettingYearWiseExpenseForChart: false
};
