export const initialState = {
	user: null,
	fetchingUser: false,
	deletingUser: false,
	loggingOut: false,
	error: null,
	loggedIn: true,
	fetchingCategories: false,
	creatingCategory: false,
	deletingCategory: false,
	updatingCategory: false,
	fetchingPaymentModes: false,
	creatingPaymentMode: false,
	deletingPaymentMode: false,
	updatingPaymentMode: false,
};
